//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public int SellerId { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public byte[] Size { get; set; }
        public Nullable<int> Weight { get; set; }
        public int Available { get; set; }
        public string Category { get; set; }
        public string Tag { get; set; }
        public string Picture { get; set; }
    
        public virtual Seller Seller { get; set; }
    }
}
