//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public Seller()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int SellerId { get; set; }
        public int UserId { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public int PhoneNumber { get; set; }
        public int Offers { get; set; }
        public int Sold { get; set; }
        public string Information { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
