//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public UserTable()
        {
            this.Sellers = new HashSet<Seller>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Zipcode { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Subscribe { get; set; }
    
        public virtual ICollection<Seller> Sellers { get; set; }
    }
}
